services:
  db:
    image: postgres:16
    container_name: gtp_db
    environment:
      POSTGRES_USER: gtp
      POSTGRES_PASSWORD: gtp_pass
      POSTGRES_DB: gtp
    ports:
      - "5432:5432"
    volumes:
      - gtp_db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: gtp_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gtp.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  gtp_db_data:
